
services:
  app:
    image: node:20-bullseye
    container_name: dating-app-frontend
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
    environment:
      # 檔案監聽（容器內常需輪詢）
      CHOKIDAR_USEPOLLING: "1"
      # DevTools 綁定 0.0.0.0 供外部瀏覽
      EXPO_DEVTOOLS_LISTEN_ADDRESS: "0.0.0.0"
      # 若需讓裝置連回主機，可自訂；留空則由 Expo 推斷
      REACT_NATIVE_PACKAGER_HOSTNAME: ""
      # Expo Dev Server 主要埠
      PORT: "8081"
      # 開發環境變數
      EXPO_PUBLIC_API_URL: "http://host.docker.internal:8080/api"
      EXPO_PUBLIC_WS_URL: "ws://host.docker.internal:6001"
      EXPO_PUBLIC_APP_STAGE: "development"
      # Node 環境
      NODE_ENV: "development"
    # Linux 建議使用 host 網路，行動裝置較易連線；macOS 不支援可改用埠對映
    # network_mode: "host"
    ports:
      - "8081:8081"   # Metro / Dev Server
      - "8082:8082"   # Expo DevTools (web UI)
      - "19000:19000" # Expo Go 連線 (classic)
      - "19001:19001" # 兼容埠
      - "19002:19002" # 兼容 DevTools
      - "19006:19006" # Expo Web (老版)
      - "5173:5173"   # Expo Web (Vite)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "
        echo '正在安裝依賴...' &&
        chown -R node:node /app/node_modules &&
        npm install &&
        echo '啟動 Expo 開發服務器...' &&
        npx expo start --port 8081 --host tunnel
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # 可選：用於執行一次性任務的服務
  tools:
    image: node:20-bullseye
    container_name: dating-app-tools
    working_dir: /app
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
    environment:
      NODE_ENV: "development"
    profiles:
      - tools
    command: ["tail", "-f", "/dev/null"]

volumes:
  app_node_modules:
    name: dating-app-frontend-node-modules

networks:
  default:
    name: dating-app-network
    external: false