[phases.build]
  cmd = "echo 'Using pre-built dist directory' && ls -la dist/ || echo 'Pre-built dist not found, attempting build...' && npm install && npm install -g @expo/cli && expo export --platform web --output-dir dist"

[phases.start]
  cmd = "npm run start:production"

[variables]
  NPM_CONFIG_PRODUCTION = "false"
  NODE_ENV = "production"
  EXPO_NO_TELEMETRY = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"