[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm run start:production"
  healthcheckPath = "/"

[env]
  # 設定 API 端點指向同專案的後端服務
  EXPO_PUBLIC_API_URL = { reference = "PUBLIC_DOMAIN", fallback = "http://localhost:8000" }